### ISSUE TITLE
First z3998:persona not styled correctly?

### ISSUE THREAD

**Issue by tuskpot** [standardebooks/christopher-morley_the-haunted-bookshop#1]
In chapter 2, there is a conversation styled as z3998:drama. Within this, each speaker's name is styled as z3998:persona. All of these "persona" names appear in small caps and right-aligned, except for the first instance, which is neither. Also, it looks like the width is not quite the same.

I can't tell why this is happening. The markup and CSS both look okay to me.

I'm seeing the issue on all of Kindle, iBooks and Calibre, so it doesn't seem like an ereader rendering error.

**Comment by acabal** [comment]
I think this is related to https://github.com/standardebooks/tools/issues/151

Not an easy fix, as the problem is a race condition in a Python library. We're working on it...
